### PR TITLE
placement_links: Aligned the links properly in the home page.

### LINKED ISSUE #90: [FEATURE]: Adding the outlined icon for the social media links
**Feature description:**
The social media links icons are not equally aligned and are of different dimensions. The icon should be outlined to give more better visual appereance.

**Use case:**
The feature is for improving the visual experience of the user scrolling through the site.

**Proposed solution:**
The icons should have same dimension and look same. 

**Screenshot of the icons:**
|Facebook|Twitter|Instagram|Linkedin|
|----|----|----|----|
|icons8-facebook-48|icons8-x-50|icons8-insta-48|icons8-linkedin-48|

### PR DESCRIPTION
**Pull request by userAdityaa**
Fixed the links placement in the home page.

## Description
Aligned the placement of the social media links that were in the home page, for better user experience.

## Related Issue
Link to the issue this PR addresses (if applicable):
- Fixes #90 

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist
- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] My code implements the changes requested in the issue.
- [x] I have added tests to cover my changes (if applicable).
- [x] I have updated the documentation (if necessary).
- [x] This PR is ready for review.

## Screenshot
Screenshot 2024-10-05 at 7 10 29 PM

## Additional Notes
Any other information that reviewers should know about this PR.

### CODE REVIEW

**Comment by userAdityaa** [comment]
Hey @VesperAkshay, Ready for review!

**Comment by VesperAkshay** [comment]
There is some issue the website is not loading after deployment please check

**Comment by userAdityaa** [comment]
> There is some issue the website is not loading after deployment please check

I am not able to get the solution to the error.
Screenshot 2024-10-05 at 7 28 44 PM

These two error might not be related to this PR ?

**Comment by VesperAkshay** [comment]
Don't worrry the error is in privious merge i will resolve it and check your PR

**Comment by VesperAkshay** [comment]
There are some error while do check

**Comment by userAdityaa** [comment]
Now, the issue should be solved. @VesperAkshay

**Comment by VesperAkshay** [comment]
Please attach a screen shot of your firebase.js

**Comment by userAdityaa** [comment]
Screenshot 2024-10-05 at 11 25 19 PM
Here.

**Comment by VesperAkshay** [comment]
Change the env variable names to that given in the readme template then push the code

**Comment by userAdityaa** [comment]
Done.

**Comment by userAdityaa** [comment]
> Change the env variable names to that given in the readme template then push the code

Done.

**Pull request merged**
