### PR TITLE
I have implemented the validation for the new users using firebase.

### LINKED ISSUE #65: [BUG] Email verification is missing from the Sign-up page.
**Description of the issue:**
**Provide a clear and concise description of the issue.**

On the sign-up page, when a user registers with an email, there is no verification process in place to confirm whether the email belongs to the user. This allows users to provide incorrect email addresses, which could result in inaccurate data being stored on the server.

**Steps to reproduce:**
1. Navigate to the sign-up page.
2. Enter an email that doesn't belong to the user (or a random invalid email address).
3. Submit the form to complete the registration.

**Expected result:**
Describe what you expected to happen.
A verification email should be sent to the registered email address. The user should only be able to complete the sign-up process after verifying the email. This ensures that the email belongs to the user and is valid.

**Actual result:**
Describe what actually happened.
The user can register and log in without email verification. This allows incorrect or fake email addresses to be used, potentially leading to inaccurate data in the system.

**System information:**

- OS: Mac OS X
- Browser: Brave

**Additional information:**
- Any other information or context.
- There is no mechanism currently in place to prompt the user to verify their email after registration.
- Email verification should be implemented to ensure data accuracy and avoid the misuse of fake email addresses.

I would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd ,Hacktober and also assign the level tag for this issue.

### PR DESCRIPTION
**Pull request by razputshivanshu**
## Description
Implemented validation for new users to prevent unauthorized access to the website. This update enhances security by ensuring that only authorized users can proceed to access restricted parts of the application.

## Related Issue
Link to the issue this PR addresses (if applicable):
- Fixes #65 

## Type of Change
- [x] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist
- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] My code implements the changes requested in the issue.
- [x] I have added tests to cover my changes (if applicable).
- [ ] I have updated the documentation (if necessary).
- [x] This PR is ready for review.

## Additional Notes
Any other information that reviewers should know about this PR.
Make sure before running this code, enable these settings from Firebase console:
Authentication > Sign In method > Enable Email/Password & Email link (passwordless sign-in)

I have tested this code from my end, and the video is here:
The video size was big, so I am linking the google drive link: 
https://drive.google.com/file/d/1eq1Y7-4DFETrgCslIIlzIP6eoD_YvLQg/view?usp=sharing

If you have any questions or need clarification, please feel free to ask in the issue comments. I’ll be available for an open discussion.

I hope you enjoyed my first contribution to the open-source project. If you liked my work, I would greatly appreciate it if you could tag this issue as level 3. It would be very helpful for me.

### CODE REVIEW

**Comment by VesperAkshay** [comment]
The code is working fine but it always ask for verification while login that is not a good idea email verification should be done on registration at time of login you can add a captcha

**Comment by razputshivanshu** [comment]
Could you explain it in a bit more detail or add some screenshots? That would be really helpful. Any suggestions on how I can improve it?

**Comment by VesperAkshay** [comment]
The email verification works on login every time a user login 
Screenshot (125)
But the email verification should work while the user is registering 

If every time user has to verify for login it will be very hectic

**Comment by razputshivanshu** [comment]
I understood. I will try to fix this in next 1-2 days.

**Comment by VesperAkshay** [comment]
Okay

**Comment by razputshivanshu** [comment]
It seems like the issue might be related to logging in with an account created before the verification feature was implemented, which could be why the verification prompt appears. On my end, I can log in without needing verification.

Here’s what I suggest to troubleshoot further:

Test 1: Try creating a new account, validate it, and then log in to see if the same issue persists. If it does, let me know, and I’ll look into it further.

If the application hasn’t been launched for real users yet, consider resetting the database to start fresh. This will clear all user data, allowing the process to function smoothly. Alternatively, you could write a JS query to trigger validation emails for existing users.

Here’s the link I used for testing on my end:
https://drive.google.com/file/d/1OwTwmOmmbItvft_w5yHBQm2-EeRj0wxp/view?usp=sharing

**Comment by VesperAkshay** [comment]
Okay I will into this and try to resolve this issue

**Comment by VesperAkshay** [comment]
One more thing in your code while registering the registration form does not have register with google option

**Comment by razputshivanshu** [comment]
> One more thing in your code while registering the registration form does not have register with google option

Ooky I missed that by mistake, I will fix that.

**Comment by VesperAkshay** [comment]
Okay

**Comment by VesperAkshay** [comment]
and if the user is old then the prompt comes for verification but for old accounts they don't email for verification

**Comment by razputshivanshu** [comment]
> One more thing in your code while registering the registration form does not have register with google option

I have updated that, you can check

**Comment by VesperAkshay** [comment]
Remove your api from the env file

**Comment by razputshivanshu** [comment]
> and if the user is old then the prompt comes for verification but for old accounts they don't email for verification

yes, that's the catch because many users has already login before the validation. Wait I will look for something so that user's who already have account can validate their emails.

**Comment by razputshivanshu** [comment]
> Remove your api from the env file

ooh sorry my bad

**Comment by razputshivanshu** [comment]
Sir, I have fixed validation for old users issue. Can you check it once?

**Comment by VesperAkshay** [comment]
All the changes are good 
Nice work

**Pull request merged**
