### PR TITLE
feat(register form): Updated the Register path's design #67

### PR DESCRIPTION
**Pull request by amber-mar**
**Description**

Given the screenshot of the design updates, I have updated the Sign Up/Register page to reflect the latest UI requests.

**Outstanding questions:**

- For smaller screens should the image be completely hidden (as is now) or stacked in a row?
- Can you provide the image from the screenshot or should I find a illustration I think works best?

Thanks!

[
Screenshot 2024-10-06 at 9 45 49 AM
](url)

## Related Issue
Link to the issue this PR addresses (if applicable): https://github.com/VesperAkshay/qr-code-generator/issues/67
- Fixes #[67]

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [x] Other (Styling updates):

## Checklist
- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] My code implements the changes requested in the issue.
- [x] I have added tests to cover my changes (if applicable).
- [x] I have updated the documentation (if necessary).
- [x] This PR is ready for review.

### CODE REVIEW

**Comment by VesperAkshay** [comment]
@amber-mar check there is some conflict

**Comment by rv-amberh** [comment]
> @amber-mar check there is some conflict

Will do!

**Comment by VesperAkshay** [comment]
> > @amber-mar check there is some conflict
> 
> Will do!

Okay

**Comment by amber-mar** [comment]
@VesperAkshay Conflicts are now resolved - thanks!

**Comment by amber-mar** [comment]
Closing this PR and will reopen as it's under the wrong account and causing issues with pushing. Will reopen shortly, thanks!

**Pull request closed without merging**
