### PR TITLE
Add social media QR code generator with hover effects

### PR DESCRIPTION
**Pull request by RajukrRaja**
Description
This PR introduces a new feature that adds social media QR code generation with hover effects and animations for the social media icons. The user can select a platform, enter a URL, and generate a QR code with the selected platform’s color and logo. It also includes improvements in the UI and customizations for size, background, and foreground colors.

Related Issue
Link to the issue addressed:

Resolves #[issue number] (Add hover effect and animation to social icons)
Change Type
Select the type of change:

 Bug fix
 New feature
 Documentation update
 Other (describe):
Checklist
 I’ve read and followed the contributing guidelines.
 Code adheres to project style and standards.
 Tests cover changes (if applicable).
 Documentation updated (if required).
 Ready for review.
Additional Notes
This feature also includes an animation using framer-motion for the social media icons. When a platform is selected, its associated color is applied to the QR code foreground. The ability to download the generated QR code is implemented. Further testing and feedback on responsiveness and cross-browser compatibility are appreciated.

### CODE REVIEW

**Comment by RajukrRaja** [comment]
please verify the changes

**Comment by RajukrRaja** [comment]
Subject: Issue with Firebase Authentication Affecting Deployment

Hi VesperAkshay

I hope this message finds you well. I'm reaching out to inform you about an issue I've encountered with the Firebase authentication implementation in our project. It seems that the current setup is causing problems that are preventing a successful deployment.

Details:
Issue: When attempting to register or authenticate users, the application fails to connect with Firebase, resulting in errors that halt the process.
Context: I've tried various debugging methods, including checking the Firebase configuration and validating the user input. However, the issue persists.
Error Message: [Include any relevant error messages you’ve received here, if applicable.]
Next Steps:
I recommend looking into the Firebase authentication settings, particularly ensuring that the API keys and configuration are correctly set up. Additionally, checking the dependencies and their versions may provide insight into potential conflicts.

Please let me know if you need any further details or if there's a good time for us to discuss this further.

Thank you for your attention to this matter!

Best regards,

Raju Kumar Raja

**Comment by RajukrRaja** [comment]
pleasse merge

**Comment by RajukrRaja** [comment]
Screenshot_20241012_093404


**Kindly please labelled as Gssoc'24 because this contribution not count on leaderboard of Gssoc'24**

**Comment by RajukrRaja** [comment]
@VesperAkshay

**Comment by Anjaliavv51** [comment]
@RajukrRaja can u add this feature to my repo , link is below

https://github.com/Anjaliavv51/Retro

**Comment by RajukrRaja** [comment]
@Anjaliavv51 which featured you are talking about, tell me more about

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 which featured you are talking about, tell me more about

This social media QR code generator on hover effect.

**Comment by RajukrRaja** [comment]
@Anjaliavv51 okay check within few minutes

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 okay check within few minutes

Okay Thank You

**Comment by RajukrRaja** [comment]
@Anjaliavv51 can you please tell me issue number

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 can you please tell me issue number

U create an issue, I will assign u immediately

**Comment by RajukrRaja** [comment]
@Anjaliavv51 kindly check

**Comment by sanjay-kv** [comment]
@VesperAkshay Please add the gssoc labels, and add me into the repo

**Pull request merged**
