### PR TITLE
Created dedicated Contributing.md file & Updated README.md with Team Section and redirect.

### LINKED ISSUE #95: [DOCS] Creation of dedicated Contributing.md file & Updation of README.md(Design)
**Contribution.md & README.md:**
image

**Description of the update:**
Currently, there is no dedicated file for contributors, such as a **Contributing.md**. Instead, the documentation for both the project and contributors is combined within the **README.md** file, which demonstrates poor documentation practices.

I intend to create a separate **Contributing.md** file so that contributors can review the contribution procedure in detail. I also plan to support new contributors by including some git commands and outlining the structure they should follow to contribute effectively to the repository.

Additionally, I want to revise the existing **README.md** file to make it more interactive and engaging.

**Reason for update:**
I believe that keeping the **README.md** focused on the project description will enhance the overall quality of the documentation. Making the **README.md** more intriguing will also increase user engagement and activity.

**Additional notes:**
N/A.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
## Description
This pull request aims to enhance the documentation and accessibility for contributors by providing a separate **Contributing.md** file, which offers a brief walkthrough to guide them in contributing to the project. It also modifies the **README.md** file by adding the following changes(screenshots provided below in the PR).

## Related Issue
Link to the issue this PR addresses (if applicable):
- Fixes #95 

## Type of Change
- [X] Bug fix
- [ ] New feature
- [X] Documentation update
- [ ] Other (please describe):

## Checklist
- [X] I have read the contributing guidelines.
- [X] I have followed the code style of this project.
- [X] My code implements the changes requested in the issue.
- [X] I have added tests to cover my changes (if applicable).
- [X] I have updated the documentation (if necessary).
- [X] This PR is ready for review.

## Screenshots:

**Before:**

- This was the previous **README.md** file
image
image

**After:**

- These are the modified sections of **README.md** file contributed by me
image
image

- This is the newly created Contributing.md file for the Contributors.
image
image

## Additional Notes
In addition to creating the **Contributing.md** file, I have also added a redirect link in the **README.md** file(Contributing Section) to guide contributors to the **Contributing.md** file after they finish reading the **README.md**. I have also changed the name to **QR Code Generator** in the **README.md** file as discussed in the issue discussion.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay Please look into the PR.

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay thanks for reviewing the PR. Also please assign the PR to me.

**Comment by rajdeepchakraborty-rc** [comment]
Thank you!

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay This should be assigned level 2
image

**Comment by rajdeepchakraborty-rc** [comment]
Thank You!

**Comment by sanjay-kv** [comment]
@VesperAkshay the level label is wrong it should be `level2` without space. 
kindly add me into the repo

**Pull request merged**
