### PR TITLE
Contribute test have raised a pr if everything goes smooth merge it to the main branch and use next js officially as ui framework prior reference 

### LINKED ISSUE #48: converting create react app to vite
converting cra to vite to enhance development experience to increase versatility of the website development across developers and enhance development speed by 65%

### PR DESCRIPTION
**Pull request by Ajdecoder**
## Related Issue
Link to the issue this PR addresses (if applicable):
- Fixes #48 

## Type of Change
conversion from create react app to next js to increase developmet speed and enhance development experience

## Checklist
- [x] have read the contributing guidelines.
- [x] have run it locally
- [x] have deployed it on vercel to analyse any potential break
- [x] I have followed the code style of this project.
- [x] My code implements the changes requested in the issue.
- [x] I have added tests to cover my changes (if applicable).
- [x] I have updated the documentation (if necessary).
- [x] This PR is ready for review.

## Additional Notes
some dependency crashed prior are fully updated

### CODE REVIEW

**Comment by Ajdecoder** [comment]
@VesperAkshay please pull latest changes if something breaks

**Comment by VesperAkshay** [comment]
Its working fine after some testing i will merge it to main

**Comment by VesperAkshay** [comment]
Thankyou for your contribution

**Comment by Ajdecoder** [comment]
Thank you so much! 🙌 I’m thrilled to have been able to contribute and be part of this project. Looking forward to more collaborations in the future!

**Pull request merged**
