### PR TITLE
[UI-Upgrate]: Changing in UI #5 

### LINKED ISSUE #5: Changing of the UI
##Update

Change the UI to very minimalistic look it should not have very tacky and very bright colors

##Inspiration
You can take inspiration from this 

Screenshot (120)
Screenshot (121)
Screenshot (122)

### PR DESCRIPTION
**Pull request by Amarjha01**
### 🛠️ Fixes Issue #5  
Closes #5 

## Description
Changing the UI of dashboard to minimalist look.

## Type of Change
- Created new nav bar.
- Created new dashboard.

## Checklist
- [ ] I have read the contributing guidelines.
- [ ] I have followed the code style of this project.
- [ ] My code implements the changes requested in the issue.
- [ ] I have added tests to cover my changes (if applicable).
- [ ] This PR is ready for review.

**Screenshot **
 - Before 
image

- After
image

### CODE REVIEW

**Comment by VesperAkshay** [comment]
@Amarjha01 there is some conflict please check

**Comment by Amarjha01** [comment]
@VesperAkshay sir please assign me and Labels with level3 without space , gssoc-ext ,hacktoberfest , hacktoberfest-accepted.

**Comment by Amarjha01** [comment]
> @Amarjha01 there is some conflict please check

sure sir

**Comment by Amarjha01** [comment]
sir can you please change level 3 to level3. This will add point in leaderboard.

**Comment by VesperAkshay** [comment]
Please check the review there is some problem the screen become blank after login @Amarjha01

**Comment by Amarjha01** [comment]
> Please check the review there is some problem the screen become blank after login @Amarjha01

@VesperAkshay Corrected the rout now after login it will redirect to /new-dashboard.

**Pull request merged**
